# DNS Server Test Configuration File

# DNS Server List
dns_servers = [
    "126.249.83.70",
    "210.245.33.106",
    "123.30.116.18",
    "124.158.7.170"
]

# Test Domain List
test_domains = [
    'google.com',
    'youtube.com',
    'facebook.com',
    'instagram.com',
    'wikipedia.org',
    'reddit.com',
    'bing.com',
    'x.com',
    'whatsapp.com',
    'chatgpt.com',
    'yahoo.com',
    'amazon.com',
    'yandex.ru',
    'duckduckgo.com',
    'tiktok.com',
    'msn.com',
    'netflix.com',
    'weather.com',
    'live.com',
    'office.com',
    'linkedin.com',
    'zoom.us',
    'canva.com',
    'fandom.com',
    'telegram.org',
    'apple.com',
    'microsoft.com',
    'samsung.com',
    'pinterest.com',
    'quora.com',
    'nytimes.com',
    'bbc.com',
    'cnn.com',
    'espn.com',
    'ebay.com',
    'adobe.com',
    'spotify.com',
    'paypal.com',
    'imgur.com',
    'stackoverflow.com',
    'wordpress.com',
    'tumblr.com',
    'walmart.com',
    'craigslist.org',
    'bbc.co.uk',
    'huffpost.com',
    'forbes.com',
    'businessinsider.com',
    'bloomberg.com',
    'usatoday.com',
    'theguardian.com',
    'foxnews.com',
    'cnbc.com',
    'npr.org',
    'washingtonpost.com',
    'time.com',
    'newsweek.com',
    'reuters.com',
    'yelp.com',
    'tripadvisor.com',
    'indeed.com',
    'glassdoor.com',
    'weather.gov',
    'accuweather.com',
    'bestbuy.com',
    'target.com',
    'homedepot.com',
    'lowes.com',
    'macys.com',
    'nasa.gov',
    'nih.gov',
    'cdc.gov',
    'fda.gov',
    'irs.gov',
    'whitehouse.gov',
    'usps.com',
    'fedex.com',
    'ups.com',
    'dhl.com',
    'ikea.com',
    'costco.com',
    'kohls.com',
    'sephora.com',
    'zillow.com',
    'bankofamerica.com',
    'chase.com',
    'wellsfargo.com',
    'citibank.com',
    'capitalone.com',
    'americanexpress.com',
    'discover.com',
    'verizon.com',
    'att.com',
    't-mobile.com',
    'sprint.com',
    'hulu.com',
    'disneyplus.com',
    'hbomax.com',
    'paramountplus.com',
    'peacocktv.com',
    'pluto.tv',
    'crunchyroll.com'
]

# DNS Resolution Configuration
DNS_TIMEOUT = 2  # Timeout (seconds)
DNS_LIFETIME = 2  # Lifetime (seconds)

# Report Configuration
REPORT_FILE = "dns_test_results.md"