# DNS Server Test Configuration File

# DNS Server List
dns_servers = [
    "124.158.7.170",
"123.30.116.18"
]

# Test Domain List — 面向全球高流量与多区域/多 TLD 的解析抽样（专线场景，非 GFW 导向）
test_domains = [
    'accuweather.com',
    'adobe.com',
    'airbnb.com',
    'aliexpress.com',
    'amazon.co.uk',
    'amazon.com',
    'amazon.de',
    'apple.com',
    'atlassian.com',
    'aws.amazon.com',
    'azure.microsoft.com',
    'bbc.co.uk',
    'bbc.com',
    'bing.com',
    'bloomberg.com',
    'booking.com',
    'canva.com',
    'chatgpt.com',
    'cloudflare.com',
    'cnn.com',
    'craigslist.org',
    'crunchyroll.com',
    'discord.com',
    'disneyplus.com',
    'dhl.com',
    'dropbox.com',
    'duckduckgo.com',
    'ebay.com',
    'elmundo.es',
    'espn.com',
    'facebook.com',
    'fedex.com',
    'fandom.com',
    'forbes.com',
    'github.com',
    'globo.com',
    'google.com',
    'hubspot.com',
    'hulu.com',
    'imdb.com',
    'imgur.com',
    'indeed.com',
    'instagram.com',
    'ikea.com',
    'lemonde.fr',
    'line.me',
    'linkedin.com',
    'live.com',
    'max.com',
    'medium.com',
    'mercadolibre.com.mx',
    'microsoft.com',
    'naver.com',
    'nasa.gov',
    'netflix.com',
    'nytimes.com',
    'nvidia.com',
    'office.com',
    'openai.com',
    'oracle.com',
    'paramountplus.com',
    'paypal.com',
    'peacocktv.com',
    'pinterest.com',
    'pluto.tv',
    'primevideo.com',
    'quora.com',
    'rakuten.co.jp',
    'reddit.com',
    'repubblica.it',
    'reuters.com',
    'roblox.com',
    'salesforce.com',
    'samsung.com',
    'shein.com',
    'shopee.com',
    'shopify.com',
    'slack.com',
    'snapchat.com',
    'soundcloud.com',
    'spiegel.de',
    'spotify.com',
    'stackoverflow.com',
    'stripe.com',
    'telegram.org',
    'theguardian.com',
    'tiktok.com',
    'tripadvisor.com',
    'tumblr.com',
    'twitch.tv',
    'ups.com',
    'weather.com',
    'whatsapp.com',
    'wikipedia.org',
    'wordpress.com',
    'x.com',
    'yahoo.com',
    'yandex.ru',
    'youtube.com',
    'zendesk.com',
    'zoom.us',
    'zara.com',
]

# DNS Resolution Configuration
TEST_ROUNDS = 3  # Number of test rounds per domain
DNS_MAX_WORKERS = 10  # Parallel workers per DNS server
DNS_TIMEOUT = 2  # Timeout (seconds)
DNS_LIFETIME = 2  # Lifetime (seconds)

# Report Configuration
REPORT_FILE = "dns_test_results.md"